[phases.setup]
archive = '7a339d87931bba829f68e94621536cad9132971a'
nixPkgs = ['nodejs']

[phases.install]
cmds = ['cd next-app && npm install']

[phases.build]
cmds = ['cd next-app && npm run build']

[start]
cmd = 'cd next-app && npm run start'
